### ISSUE TITLE
Realm no discovered

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/linuxmuster-linuxclient7#23]
Hello,

I ran this week-end into an error while installing a new client : 

```
realm discover --name-only
```

was not able to discover the realm in the network. I don't know exactly why, and must investigate DHCP on the server.
However I think it would be useful to add a fallback in [discoverDomain](https://github.com/linuxmuster/linuxmuster-linuxclient7/blob/6a86e3ddeb75b59e8d1ae71001e2699c94e920c8/usr/lib/python3/dist-packages/linuxmusterLinuxclient7/realm.py#L78) (and maybe in others functions) in order to let the user manually specify the realm. 

Thanks

Arnaud

**Comment by CodeCrafter912** [comment]
Hi Arnaud,

I am not sure if an override would help, as the domain is joined using realm join, which would probably also be unable to discover it.
Can you try to manually join the domain on your affected machine using `realm jon <domain>`? If this works, an override would make sense, otherwise it would not.

Regards, 
Dorian

**Comment by kiarn** [comment]
Hi @CodeCrafter912 

I think it was possible after the fail, but since I'm not able to reproduce this behaviour, I can close this issue for the moment ( maybe it was only a temporary dhcp/dns problem ).

Cheers,

Arnaud
